import { Award, Shield, TrendingUp } from "lucide-react"

export type SiteConfig = typeof siteConfig

export const siteConfig = {
  name: "Linkor",
  app: "https://app.linkor.host",
  description:
    "A Linkor oferece serviços para potencializar seus serviços digitais para tudo que seu projeto precisa e uma equipe que está sempre disposta a te levar ao sucesso.",
  promoCard: {
    active: false,
    items: [
      {
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DV%20WHATSAPP-JfqpYpH7Ye56LN6S0ldMWFHv0Ztgua.png",
        title: "AMD Ryzen™ 9 7900X",
        subtitle: "4.7GHz - Até 5.6 GHz",
        features: [
          "2vCPU Ryzen 9",
          "2GB RAM DDR5",
          "40GB NVME",
          "1 IPv4 (/32)",
          "1 IPv6 (/128)",
          "Windows 2012 Até 2025!",
        ],
        price: "50,00",
        originalPrice: "99,00",
        ctaText: "Contratar Agora",
      },
      {
        image:
          "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/natal-linkor-500x500-ovjTWyNV5J1tUBBmy6Gz4K8ofaprLI.png",
        title: "cPanel ECO-5",
        subtitle: "Perfeito para iniciantes",
        features: [
          "Hospedagem para um domínio",
          "5 GB de armazenamento NVMe",
          "1 Conta de e-mail grátis",
          "Tráfego Ilimitado",
          "Litespeed Webserver + QUIC.cloud",
          "Backup semanal",
        ],
        price: "6,99",
        ctaText: "Aproveitar Oferta",
        isChristmas: true,
      },
    ],
  },
  navItems: [
    {
      label: "Inicio",
      href: "/",
    },
  ],
  gameServer: { link: "#planos-vps" },
  cpanelPlans: [
    {
      id: "start",
      name: "Start",
      link: "https://app.linkor.host/store/hospedagem-de-site/start",
      price: "29,99",
      annualPrice: "17,99",
      storage: "10 GB SSD",
      bandwidth: "Ilimitado",
      domains: "Tenha sites ilimitados",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "WordPress Toolkit", included: true, highlight: false },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "PHP + NodeJS + Ruby + Python", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: false, highlight: false },
        { text: "IP dedicado", included: false, highlight: true },
        { text: "Recursos dedicados", included: false, highlight: true },
      ],
    },
    {
      id: "plus",
      name: "Plus",
      link: "https://app.linkor.host/store/hospedagem-de-site/plus",
      price: "39,99",
      annualPrice: "23,99",
      storage: "50 GB NVMe",
      bandwidth: "Ilimitado",
      domains: "Tenha sites ilimitados",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "WordPress Toolkit", included: true, highlight: false },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "PHP + NodeJS + Ruby + Python", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: true, highlight: true },
        { text: "IP dedicado", included: false, highlight: true },
        { text: "Recursos dedicados", included: false, highlight: true },
      ],
      recommended: true,
    },
    {
      id: "ultra",
      name: "Ultra",
      link: "https://app.linkor.host/store/hospedagem-de-site/ultra",
      price: "69,99",
      annualPrice: "41,99",
      storage: "100 GB NVMe",
      bandwidth: "Ilimitado",
      domains: "Tenha sites ilimitados",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "WordPress Toolkit", included: true, highlight: false },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "PHP + NodeJS + Ruby + Python", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: true, highlight: false },
        { text: "IP dedicado", included: true, highlight: true },
        { text: "Recursos dedicados", included: true, highlight: true },
      ],
    },
  ],
  pleskPlans: [
    {
      id: "level1",
      name: "Level 1",
      link: "https://app.linkor.host/store/hospedagem-de-site-gamer/site-gamer-level-1",
      price: "9,99",
      annualPrice: "5,99",
      storage: "2 GB NVMe",
      bandwidth: "Ilimitado",
      domains: "Tenha até 1 site",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "vCPU AMD Ryzen", included: true, highlight: false },
        { text: "4 GB RAM DDR5", included: true, highlight: false },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: false, highlight: false },
        { text: "IP dedicado", included: false, highlight: true },
        { text: "Recursos dedicados", included: false, highlight: true },
      ],
    },
    {
      id: "level2",
      name: "Level 2",
      link: "https://app.linkor.host/store/hospedagem-de-site-gamer/site-gamer-level-2",
      price: "19,99",
      annualPrice: "11,99",
      storage: "5 GB NVMe",
      bandwidth: "Ilimitado",
      domains: "Tenha até 3 sites",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "vCPU AMD Ryzen", included: true, highlight: false },
        { text: "6 GB RAM DDR5", included: true, highlight: false },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: false, highlight: false },
        { text: "IP dedicado", included: false, highlight: true },
        { text: "Recursos dedicados", included: false, highlight: true },
      ],
      recommended: true,
    },
    {
      id: "level3",
      name: "Level 3",
      link: "https://app.linkor.host/store/hospedagem-de-site-gamer/site-gamer-level-3",
      price: "29,99",
      annualPrice: "17,99",
      storage: "10 GB NVMe",
      bandwidth: "Ilimitado",
      domains: "Tenha até 5 sites",
      databases: "Bancos de dados Ilimitados",
      features: [
        { text: "1 Licença cPanel", included: true },
        { text: "vCPU AMD Ryzen", included: true, highlight: false },
        { text: "8 GB RAM DDR5", included: true, highlight: false },
        { text: "LiteSpeed Web Server", included: true, highlight: false },
        { text: "Email @seudominio.com.br", included: true },
        {
          text: "Backup grátis todos os dias",
          included: true,
          tooltip: "Backups automáticos com retenção de 7 dias",
        },
        { text: "Certificado de segurança SSL", included: true },
        { text: "Migração de site grátis", included: true },
        { text: "Cache avançado", included: true },
        {
          text: "Proteção Imunify360",
          included: true,
          highlight: false,
        },
        { text: "Proteção Cloudflare", included: true },
        { text: "Seletor PHP 5.6 a 8.4", included: true },
        { text: "Bônus PRO DOWNLOADS", included: true },
        { text: "Suporte prioritário", included: false, highlight: false },
        { text: "IP dedicado", included: false, highlight: true },
        { text: "Recursos dedicados", included: false, highlight: true },
      ],
    },
  ],
  vpsPlans: [
    {
      id: "intel",
      name: "INTEL XEON",
      allPlans: "https://app.linkor.host/store/vps-gamer-intel",
      plans: [
        {
          id: "starter",
          name: "PLANO 4R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-4r",
          specs: "2 núcleos • 4GB RAM • 40GB SSD • Anti DDoS Incluso",
          price: "59,94",
          color: "#3B82F6",
        },
        {
          id: "advanced",
          name: "PLANO 8R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-8r",
          specs: "4 núcleos • 8GB RAM • 60GB SSD • Anti DDoS Incluso",
          price: "119,94",
          color: "#3B82F6",
        },
        {
          id: "enterprise",
          name: "PLANO 12R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-12r",
          specs: "6 núcleos • 12GB RAM • 80GB SSD • Anti DDoS Incluso",
          price: "179,94",
          color: "#3B82F6",
        },
        {
          id: "premium",
          name: "PLANO 16R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-16r",
          specs: "8 núcleos • 16GB RAM • 100GB SSD • Anti DDoS Incluso",
          price: "239,94",
          color: "#3B82F6",
        },
        {
          id: "ultimate",
          name: "PLANO 20R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-20r",
          specs: "10 núcleos • 20GB RAM • 120GB SSD • Anti DDoS Incluso",
          price: "299,94",
          color: "#3B82F6",
        },
        {
          id: "extreme",
          name: "PLANO 24R",
          link: "https://app.linkor.host/store/vps-gamer-intel/plano-24r",
          specs: "12 núcleos • 24GB RAM • 140GB SSD • Anti DDoS Incluso",
          price: "359,94",
          color: "#3B82F6",
        },
      ],
    },
    {
      id: "ryzen7900",
      name: "AMD RYZEN",
      allPlans: "https://app.linkor.host/store/vps-gamer-amd",
      plans: [
        {
          id: "starter",
          name: "PLANO 4R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-4r",
          specs: "2 núcleos • 4GB RAM • 40GB SSD • Anti DDoS Incluso",
          price: "99,94",
          color: "#F04339",
        },
        {
          id: "advanced",
          name: "PLANO 8R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-8r",
          specs: "4 núcleos • 8GB RAM • 60GB SSD • Anti DDoS Incluso",
          price: "159,94",
          color: "#F04339",
        },
        {
          id: "enterprise",
          name: "PLANO 12R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-12r",
          specs: "6 núcleos • 12GB RAM • 80GB SSD • Anti DDoS Incluso",
          price: "219,94",
          color: "#F04339",
        },
        {
          id: "premium",
          name: "PLANO 16R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-16r",
          specs: "8 núcleos • 16GB RAM • 100GB SSD • Anti DDoS Incluso",
          price: "279,94",
          color: "#F04339",
        },
        {
          id: "ultimate",
          name: "PLANO 20R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-20r",
          specs: "10 núcleos • 20GB RAM • 120GB SSD • Anti DDoS Incluso",
          price: "339,94",
          color: "#F04339",
        },
        {
          id: "extreme",
          name: "PLANO 24R",
          link: "https://app.linkor.host/store/vps-gamer-amd/plano-24r",
          specs: "12 núcleos • 24GB RAM • 140GB SSD • Anti DDoS Incluso",
          price: "399,94",
          color: "#F04339",
        },
      ],
    },
  ],
  partners: [
    {
      name: "Envato Elements",
      logo: "/conteudos/provider_envato.svg",
      width: 180,
      height: 60,
    },
    {
      name: "Freepik",
      logo: "/conteudos/provider_freepik.svg",
      width: 70,
      height: 20,
    },

    {
      name: "Flaticon",
      logo: "/conteudos/provider_flaticon.svg",
      width: 180,
      height: 60,
    },
    {
      name: "GPL Vault",
      logo: "/conteudos/provider_gplvault.svg",
      width: 180,
      height: 60,
    },
    {
      name: "Storyblocks",
      logo: "/conteudos/provider_storyblocks.png",
      width: 180,
      height: 60,
    },
    {
      name: "Motion Array",
      logo: "/conteudos/provider_motionarray.svg",
      width: 180,
      height: 60,
    },
    {
      name: "IconScout",
      logo: "/conteudos/provider_iconscout.png",
      width: 180,
      height: 60,
    },
    {
      name: "GPLZONE",
      logo: "/conteudos/provider_gplzone.svg",
      width: 180,
      height: 60,
    },
    {
      name: "FestingerVault",
      logo: "/conteudos/provider_festingervault.svg",
      width: 180,
      height: 60,
    },
    {
      name: "Artlist",
      logo: "/conteudos/provider_artlist.svg",
      width: 180,
      height: 60,
    },
    {
      name: "ProductionCrate",
      logo: "/conteudos/provider_productioncrate.svg",
      width: 180,
      height: 60,
    },
  ],
  categories: [
    {
      title: "IMAGENS, VETORES E FOTOS",
      count: "+20 milhões",
      description: "Fotos, vetores, vídeos, PSDs e modelos gráficos prontos para usar.",
    },
    {
      title: "MODELOS, FONTES E ÁUDIOS",
      count: "+900.000",
      description: "Bibliotecas completas com apresentações, vídeos, fontes e elementos 3D.",
    },
    {
      title: "TEMAS E PLUGINS WORDPRESS",
      count: "+20.000",
      description: "Inclui temas e plugins premium WordPress e extensões para ecommerce.",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Miguel Oliveira",
      role: "CEO",
      company: "TechSolutions",
      image: "/professional-headshot.png",
      rating: 5,
      text: "Desde que migramos para a Linkor, os tempos de carregamento do nosso site diminuíram em 70%. A infraestrutura deles é sólida e a equipe de suporte é incrivelmente responsiva. Melhor decisão que tomamos para nosso e-commerce em crescimento.",
    },
    {
      id: 2,
      name: "Fernanda Lima",
      role: "CTO",
      company: "WebDev Brasil",
      image:
        "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/FRAME-HOSPEDAGEMDESITES-zh2E6tATHuF7TpcnhHWfJBeTV1ntJq.png",
      rating: 5,
      text: "Nossa experiência com a Linkor tem sido fantástica. Desde a hospedagem até as soluções empresariais, cada aspecto foi tratado com dedicação. Nosso site em WordPress nunca funcionou tão bem.",
    },
    {
      id: 3,
      name: "Carlos Santos",
      role: "Fundador",
      company: "AppStart",
      image: "/professional-man-headshot.png",
      rating: 5,
      text: "À medida que nossa startup cresceu de 10.000 para 1 milhão de usuários, a Linkor cresceu conosco sem esforço. Sua infraestrutura de escalonamento automático lidou com picos de tráfego perfeitamente.",
    },
    {
      id: 4,
      name: "Ana Beatriz",
      role: "Diretora de Marketing",
      company: "E-commerce Express",
      image: "/professional-woman-headshot.png",
      rating: 5,
      text: "A velocidade de carregamento do nosso site melhorou drasticamente após migrarmos para a Linkor. Nossas taxas de conversão aumentaram 35% apenas por causa da melhoria no desempenho. O suporte técnico é excepcional.",
    },
    {
      id: 5,
      name: "Roberto Mendes",
      role: "Desenvolvedor Full Stack",
      company: "DevHouse",
      image: "/professional-man-headshot.png",
      rating: 4,
      text: "Como desenvolvedor, aprecio muito as ferramentas que a Linkor oferece. O ambiente de staging, os pipelines de CI/CD e a facilidade de implantação tornaram meu fluxo de trabalho muito mais eficiente.",
    },
    {
      id: 6,
      name: "Juliana Costa",
      role: "Gerente de Projetos",
      company: "Agência Digital",
      image: "/professional-woman-headshot.png",
      rating: 5,
      text: "Gerenciar múltiplos projetos web se tornou muito mais fácil com a Linkor. O painel de controle intuitivo e as ferramentas de monitoramento nos ajudam a manter tudo funcionando perfeitamente.",
    },
    {
      id: 7,
      name: "Marcelo Alves",
      role: "Proprietário",
      company: "Loja Virtual MegaShop",
      image: "/professional-headshot.png",
      rating: 5,
      text: "Minha loja virtual nunca esteve tão estável. Mesmo durante a Black Friday, com tráfego 10x maior que o normal, o site permaneceu rápido e responsivo. A proteção DDoS da Linkor realmente funciona!",
    },
    {
      id: 8,
      name: "Camila Ferreira",
      role: "Arquiteta de Software",
      company: "TechInnovate",
      image: "/professional-woman-headshot.png",
      rating: 4,
      text: "A flexibilidade da infraestrutura da Linkor nos permitiu escalar conforme necessário. Começamos com um plano básico e crescemos gradualmente sem nenhum tempo de inatividade durante as migrações.",
    },
    {
      id: 9,
      name: "Paulo Henrique",
      role: "Diretor de TI",
      company: "Grupo Empresarial",
      image: "/professional-man-headshot.png",
      rating: 5,
      text: "Após avaliar vários provedores de hospedagem, escolhemos a Linkor pela combinação de desempenho, segurança e custo-benefício. Três anos depois, continuamos extremamente satisfeitos com nossa decisão.",
    },
  ],
  googleReviews: {
    qntdReviews: "53",
    stars: {
      5: "100%",
      4: "0%",
      3: "0%",
      2: "0%",
      1: "0%",
    },
    averageRating: "5",
    Reputation: "Ótima",
    Index: "10",
    Answered: "100%",
    Solution: "100%",
    description: "A Linkor demonstra excelência no atendimento ao cliente, nenhuma reclamação nos últimos 3 anos.",
    subDescription: "— Análise Reclame Aqui, 2025",
    reviews: [
      {
        name: "Tiago Martins",
        star: 5,
        description:
          "Melhor empresa em todos os sentidos! Serviços, atendimento e suporte... Se tem uma empresa que eu recomendo, é essa!!",
      },
      {
        name: "Liny Gomes",
        star: 5,
        description:
          "Migrei meu e-commerce para a Linkor e a diferença foi impressionante. Velocidade, estabilidade e suporte de primeira.",
      },
    ],
    certifications: [
      {
        title: "Melhor Startup 2025",
        subTitle: "Euro Awards",
        icon: Award,
      },
      {
        title: "Melhor Custo-Benefício",
        subTitle: "Raking Hosting Brasil",
        icon: TrendingUp,
      },
      {
        title: "Certificações válidas",
        subTitle: "LWS Segurança da Informação",
        icon: Shield,
      },
    ],
  },
}
